<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFb6rKfB\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFb6rKfB/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFb6rKfB.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFb6rKfB\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerFb6rKfB\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Fb6rKfB',
    'container.build_id' => '391b3d85',
    'container.build_time' => 1563530498,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFb6rKfB');
